# Generated by Django 6.0.1 on 2026-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_flight_seats_available_dealbooking_packagebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_type',
            field=models.CharField(default='Boeing 737', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='baggage_allowance',
            field=models.CharField(default='20kg', max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
