# Generated by Django 6.0.1 on 2026-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_flight_aircraft_type_flight_baggage_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='international', max_length=20),
        ),
    ]
